# Generated by Django 4.0.3 on 2022-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(verbose_name='Data do Evento'),
        ),
    ]
